baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

[params.profileMode]
enabled = 'true'
defaultTheme = 'auto' #dark, light
title = 'gray compass'
subtitle = 'by Abraham Ruiz'

[[params.profileMode.buttons]]
name = 'letters'
url = '/posts'

[[params.socialIcons]]
name = 'mastodon'
rel = 'me'
url = 'https://spore.social/@abe'
href = 'https://spore.social/@abe'