baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'
color = 'linen'


[params.profileMode]
enabled = 'true'
defaultTheme = 'auto'
title = 'Abraham Ruiz'
subtitle = 'A Research Coordinator at Workers Defense Project. And overall general hobbyist that loves to get in over his head learning new things.'

[[params.profileMode.buttons]]
name = 'posts'
url = '/posts'

[[params.socialIcons]]
name = 'mastodon'
rel = 'me'
url = 'https://spore.social/@abe'
href = 'https://spore.social/@abe'

[[params.socialIcons]]
name = 'email'
href = 'mailto:00_webpage_carton@icloud.com?I found you through your website'
mailto = '00_webpage_carton@icloud.com'
url = 'mailto:00_webpage_carton@icloud.com?subject=Hi, I found you through your website'