baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

Params:
	HomeInfoParams:
		Title: gray compass
		Content: by Abraham Ruiz
	Social Icons:
		- name: "<mastodon>"
		- url:	"<a rel="me" href="https://spore.social/@abe">Mastodon</a>"
