baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = 'gray compass'
subtitle = 'by Abraham Ruiz"

[[params.profileMode.buttons]]
name = 'letters'

[params.profileMode.buttons]]
url = '/posts'

[[params.socialIcons]]
name = 'mastodon'

[[params.socialIcons]]
Url = "rel="me" href="https://spore.social/@abe"