baseURL = 'https://graycompass.com/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

[params]
favicon = '/static/favicon.ico' #favicon = "<link /static/favicon.ico>"

[assets]
disableHLJS = 'true'
favicon = "<link /static/favicon.ico>"

[params.profileMode]
enabled = 'true'
defaultTheme = 'auto'
title = 'Abraham Ruiz'
subtitle = 'Research Coordinator at Workers Defense Project. And general hobbyist that loves to get in over my head learning new things.'

[[params.profileMode.buttons]]
name = 'posts'
url = '/posts'

[[params.socialIcons]]
name = 'mastodon'
rel = 'me'
url = 'https://spore.social/@abe'
href = 'https://spore.social/@abe'

[[params.socialIcons]]
name = 'email'
url = 'mailto:00_webpage_carton@icloud.com?subject=Hi, I found you through your website'