baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

[params.homeInfoParams]
title='gray compass'
content= 'Abraham Ruiz'

[[params.socialIcons]]
name = 'mastodon'
rel = 'me'
href = 'https://spore.social/@abe'