baseURL = 'https://graycompass.co/'
languageCode = 'en-us'
title = 'gray compass'
theme = 'PaperMod'

[params.homeInfoParams]
Title='gray compass'
Content: 'Abraham Ruiz'

[[params.socialIcons]]
name: "mastodon"
url="<a rel="me" href="https://spore.social/@abe">Mastodon</a>"
